services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: mydb
    secrets:
      - postgres_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: "postgresql+psycopg2://user:password@db:5432/mydb"
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: /backend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app_net
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data: {}

networks:
  app_net:
    driver: bridge

secrets:
  postgres_password:
    file: ./database/postgres_password
