services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: mydb
    secrets:
      - postgres_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      SERVICE_HOST: localhost
      SERVICE_PORT: 5000
      FRONTEND_URL: http://localhost:3000
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      # args:
      #   NEXT_PUBLIC_BACKEND_URL: http://localhost:5000
    environment:
      SERVICE_HOST: localhost
      SERVICE_PORT: 3000
      NEXT_PUBLIC_BACKEND_URL: http://localhost:5000
    ports:
      - "3000:3000"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "node", "/app/healthcheck.js"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data: {}

networks:
  app_net:
    driver: bridge

secrets:
  postgres_password:
    file: ./database/postgres_password
