site_name: CI/CD Multicontainer Project
site_description: Documentation for the CI/CD Multicontainer Project.
theme:
  name: material
  palette:
    primary: indigo
    accent: cyan
nav:
  - Home: index.md
  - Overview:
      - API Documentation: api.md
      - Architecture: architecture.md
  - Guidelines: guidelines.md
  - Project Report: project-report.md
repo_url: https://gitlab.com/ella.mzg/ci-cd-multicontainer-project
repo_name: CI/CD Multicontainer Project
