[[ruleset]]
name = "SAST Ruleset"
description = "Ruleset for stricter SAST checks on Python and JavaScript"

[ruleset.rules]
include = ["critical", "high", "medium", "low"]

[[ruleset.custom_rules]]
languages = ["python", "javascript"]
pattern = "(api_key|auth_token|password\\s*=\\s*[\"'].*[\"'])"
severity = "critical"
confidence = "high"
description = "Hardcoded sensitive keys or passwords detected."

[[ruleset.custom_rules]]
languages = ["python", "javascript"]
pattern = "(exec\\(|eval\\(|document.write\\()"
severity = "high"
confidence = "medium"
description = "Dangerous functions (exec, eval, document.write) detected."

[[ruleset.custom_rules]]
languages = ["python"]
pattern = "(os.system\\(|subprocess\\.Popen\\()"
severity = "medium"
confidence = "medium"
description = "Potentially unsafe shell commands detected in Python."

[[ruleset.custom_rules]]
languages = ["javascript"]
pattern = "(innerHTML\\s*=|location\\.href\\s*=)"
severity = "medium"
confidence = "medium"
description = "Potential DOM-based XSS vulnerability in JavaScript."
